version: '3'

services:

    app:
        build: .
        container_name: bank-api-php
        restart: always
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - bank-api-network
networks:
    bank-api-network:
        driver: bridge